### ISSUE TITLE
Text on right booking widget disappear when hovered

### ISSUE THREAD

**Issue by paulosamson** [ebureauet/frontend-sidel#2]
video: http://screencast.com/t/HlprtxlybJ0

**Comment by teej043** [comment]
@paulosamson It is now fixed. Updated styles.css on svn.

**Comment by paulosamson** [comment]
@teej043  awesome. thanks!

**Comment by paulosamson** [comment]
https://github.com/ebureauet/frontend-sidel/commit/d6c19c89c6e125687bd15c360dec82ba4c5a2058
