### ISSUE TITLE
Right widgets bug on other pages after updates from training section

### ISSUE THREAD

**Issue by paulosamson** [ebureauet/frontend-sidel#3]
http://screencast.com/t/gHXvkSWI6i

Editing the width to 200px will fix the problem.

**Comment by teej043** [comment]
@paulosamson this is fixed, a width of 230px seems enough. the 200px will force the line to break too early, hence http://screencast.com/t/5SYmOZ7auHhv

**Comment by paulosamson** [comment]
thanks
